services:
  postgres:
    image: postgres:16-alpine
    container_name: leansim-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-leansim}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-leansim_password}
      - POSTGRES_DB=${POSTGRES_DB:-leansim}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-leansim}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Herramienta de administración de base de datos pgAdmin (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: leansim-pgadmin
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@leansim.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:
