#!/bin/sh
command -v fnm >/dev/null 2>&1 && eval "$(fnm env --use-on-cd)" || true

echo "🧪 Running tests before push..."

# Run unit and integration tests
npm run test

# Check test results
if [ $? -ne 0 ]; then
    echo "❌ Tests failed. Push aborted."
    exit 1
fi

echo "✅ All tests passed. Push allowed."
